runners:
  - name: cirun-gcp-aarch64-runner
    cloud: gcp
    instance_type: n4a-standard-32
    machine_image: ubuntu-minimal-2404-noble-arm64-v20260507
    region: us-east1-b
    preemptible: true
    extra_config:
      baseDisk:
        diskSizeGb: 60
    labels:
      - cirun-gcp-aarch64

  - name: cirun-gcp-x86-runner
    cloud: gcp
    instance_type: c4d-standard-32
    machine_image: ubuntu-2404-noble-amd64-v20260503
    region: us-east1-b
    preemptible: true
    extra_config:
      baseDisk:
        diskSizeGb: 60
    labels:
      - cirun-gcp-x86
